# # Première configuration
    # version: '3'
    # services:
    #   web:
    #     build: .
    #     command: python backend/manage.py runserver 0.0.0.0:8000
    #     volumes:
    #       - ./backend:/app/src
    #     ports:
    #       - 8000:8000

version: "3"
services:
  client:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./front/dist:/usr/share/nginx/html
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - ./backend:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=rh_solution
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
      - MYSQL_ROOT_PASSWORD=0000
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/mysql

volumes:
  pgdb:
