version: "3"
services:
  client:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=rh_solution
      - MYSQL_PASSWORD=0000
      - MYSQL_ROOT_PASSWORD=0000
    ports:
      - 3306:3306
    volumes:
      - pgdb:/var/lib/mysql

volumes:
  pgdb:

