# Generated by Django 4.2.2 on 2023-06-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "ID_User",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                ("First_Name", models.CharField(db_column="First_Name", max_length=15)),
                ("Last_Name", models.CharField(db_column="Last_Name", max_length=15)),
                ("Email", models.EmailField(db_column="Email", max_length=20)),
                (
                    "Personnal_Email",
                    models.EmailField(db_column="Personnal_Email", max_length=20),
                ),
                ("Phone_Number", models.IntegerField(db_column="Phone_Number")),
                ("Gender", models.CharField(db_column="Gender", max_length=15)),
            ],
        ),
    ]
